### ISSUE TITLE
How to run these codes?

### ISSUE THREAD

**Issue by Strider20151** [jaswanth04/Ensemble_techniques_parallel#1]
When I run these codes, it found error. Can you tell me the run sequence of these codes?

**Comment by jaswanth04** [comment]
Hi, Thanks for trying to use it. I had written a sample code in src/python folder. 
The files are by the name *_trial.py. You can look at those codes to get an idea.

The folder by ensembles_parallel is the python package which implements the ensemble methods in parallel. 

Please let me know, if I need to do any improvements. Thanks.
